// frontend/src/components/RegisterPage.vue
<template>
  <v-container class="d-flex justify-center align-center fill-height">
    <v-card class="pa-6" width="400">
      <v-card-title class="text-h6">Регистрация</v-card-title>
      <v-card-text>
        <v-form @submit.prevent="handleRegister" ref="form">
          <v-text-field
            v-model="name"
            label="Имя"
            prepend-icon="mdi-account"
            required
          />

          <v-text-field
            v-model="email"
            label="Email"
            type="email"
            prepend-icon="mdi-email"
            required
          />

          <v-text-field
            v-model="password"
            label="Пароль"
            type="password"
            prepend-icon="mdi-lock"
            required
          />

          <v-text-field
            v-model="key"
            label="Ключ регистрации"
            prepend-icon="mdi-key"
            required
          />

          <v-alert
            v-if="error"
            type="error"
            class="mb-4"
            dense
          >
            {{ error }}
          </v-alert>

          <v-btn
            type="submit"
            color="primary"
            block
            :loading="loading"
          >
            Зарегистрироваться
          </v-btn>
        </v-form>

        <v-divider class="my-4"></v-divider>

        <div class="text-center">
          <span class="text-body-2">Уже есть аккаунт?</span>
          <v-btn
            variant="text"
            color="primary"
            @click="$router.push('/login')"
            class="ml-2"
          >
            Войти
          </v-btn>
        </div>
      </v-card-text>
    </v-card>
  </v-container>
</template>

<script setup>
import { ref } from 'vue'
import { useAuthStore } from '../stores/auth.js'
import { useRouter } from 'vue-router'

const auth = useAuthStore()
const router = useRouter()

const name = ref('')
const email = ref('')
const password = ref('')
const key = ref('')
const error = ref('')
const loading = ref(false)

const handleRegister = async () => {
  error.value = ''
  loading.value = true

  try {
    await auth.register({ 
      name: name.value,
      email: email.value, 
      password: password.value,
      key: key.value
    })
    router.push('/tasks') // после регистрации редирект
  } catch (e) {
    error.value = e.message
  } finally {
    loading.value = false
  }
}
</script>

// frontend/src/pages/RegisterPage.tsx
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { apiClient } from '../lib/api';
import toast from 'react-hot-toast';
import { useAuthStore } from '../stores/authStore';

export default function RegisterPage() {
  const navigate = useNavigate();
  const { fetchUser } = useAuthStore();
  const [form, setForm] = useState({
    name: '',
    email: '',
    password: '',
    key: '',
    telegramId: '',
  });
  const [isLoading, setIsLoading] = useState(false);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setForm({ ...form, [e.target.name]: e.target.value });
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsLoading(true);
    try {
      await apiClient.register({
        name: form.name,
        email: form.email,
        password: form.password,
        key: form.key,
        telegramId: form.telegramId ? Number(form.telegramId) : 0,
      });
      await apiClient.login({ email: form.email, password: form.password });
      await fetchUser();
      toast.success('Регистрация успешна!');
      navigate('/dashboard');
    } catch (error: any) {
      const resp = error?.response?.data;
      const msg = typeof resp === 'string'
        ? resp
        : (resp?.error || resp?.message || error?.message || 'Ошибка регистрации');
      toast.error(String(msg));
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-primary-50 to-primary-100">
      <div className="card max-w-md w-full">
        <div className="text-center mb-8">
          <h1 className="text-3xl font-bold text-gray-900">Регистрация</h1>
          <p className="text-gray-600 mt-2">Введите данные и ключ регистрации</p>
        </div>
        <form onSubmit={handleSubmit} className="space-y-6">
          <div>
            <label htmlFor="name" className="block text-sm font-medium text-gray-700 mb-2">
              Имя
            </label>
            <input
              id="name"
              name="name"
              type="text"
              value={form.name}
              onChange={handleChange}
              required
              className="input"
              placeholder="Введите имя"
            />
          </div>
          <div>
            <label htmlFor="email" className="block text-sm font-medium text-gray-700 mb-2">
              Email
            </label>
            <input
              id="email"
              name="email"
              type="email"
              value={form.email}
              onChange={handleChange}
              required
              className="input"
              placeholder="your@email.com"
            />
          </div>
          <div>
            <label htmlFor="password" className="block text-sm font-medium text-gray-700 mb-2">
              Пароль
            </label>
            <input
              id="password"
              name="password"
              type="password"
              value={form.password}
              onChange={handleChange}
              required
              className="input"
              placeholder="••••••••"
            />
          </div>
          <div>
            <label htmlFor="key" className="block text-sm font-medium text-gray-700 mb-2">
              Ключ регистрации
            </label>
            <input
              id="key"
              name="key"
              type="text"
              value={form.key}
              onChange={handleChange}
              required
              className="input"
              placeholder="Вставьте ключ от администратора"
              autoComplete="off"
            />
          </div>
          <div>
            <label htmlFor="telegramId" className="block text-sm font-medium text-gray-700 mb-2">
              Telegram ID (число)
            </label>
            <input
              id="telegramId"
              name="telegramId"
              type="number"
              value={form.telegramId}
              onChange={handleChange}
              className="input"
              placeholder="Например, 123456789"
            />
          </div>
          <button
            type="submit"
            disabled={isLoading}
            className="btn btn-primary w-full"
          >
            {isLoading ? 'Регистрация...' : 'Зарегистрироваться'}
          </button>
          <div className="text-center pt-4 text-sm">
            Уже есть аккаунт?{' '}
            <a href="/login" className="text-primary-600 hover:underline">Войти</a>
          </div>
        </form>
      </div>
    </div>
  );
}
